#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & 

wmname LG3D &
vmware-user-suid-wrapper & 

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle   true
bspc config focus_follows_pointer true
bspc config border_width 2
bspc config normal_border_color   #B50000


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

/usr/bin/feh feh --bg-fill /home/bl4ckm4mb4/Escritorio/bl4ckm4mb4/Fondos/kalii.png &
~/.config/polybar/./launch.sh & 
picom &


